### ISSUE TITLE
USBPorts info.plist Model less possible?

### ISSUE THREAD

**Issue by cattyhouse** [headkaze/Hackintool#49]
i found that under `USBPorts/info.plistI/OKitPersonalities`, there are 2 lines of model related information:

````
iMac19,2-XHC
````
and
````
model iMac19,2
````

Wonder if these information can be eliminated during generation of USBPorts? 
e.g. `iMac19,2-XHC` -> `XHC` and delete `model` key

So that the kext can be used with other models when needed.
e.g. switching from iMac19,2 to MacPro7,1

thanks

**Comment by headkaze** [comment]
Try removing it and see if it works? I think it's necessary.

**Comment by zearp** [comment]
It is necessary. While I haven't outright removed it I did have weird issues that could be related to this not 100% sure but web search led me here. 

When the model in the Info.plist didn't match up with the one used on the machine strange things happened here. Like usb3 ports turning into usb2 ports after a few devices have been plugged in and out.

It would be nice if the same kext could be used one the same pc's that only differ in cpu or have a dGPU that requires a model change (to get DRM working). I have some Dell 7020 desktops and depending on the cpu the model changes (14,1, 14,3, 15,1, etc). Using the same USBPorts.kext on all of them would be nice and clean and also gets rid of another "binary" kext.

A work around I use now is to use the generated .aml files with USBInjectAll. There are no references to models in the aml files. Maybe this work around can also help @cattyhouse.

Just using a plist kext instead of USBInjectAll would be ideal and maybe more vanilla but to me this is a very minor issue. I've build so many port maps with Hackintool, having to do those manually would be such a chore. Many thanks for your hard work.

For the fun of it I renamed both instances of _iMac14,3_ to _iMac_ to see what actually happens and here's the results. Probably a big enough mismatch to cause issues, and maybe the weird issues I had encountered when I used the same USBPorts.kext on the same systems that had different model names configured.

Sorry for the wall of text...

![renamed](https://user-images.githubusercontent.com/63272687/79084568-bc59e200-7d34-11ea-9c03-163c489be5d2.png)
![original](https://user-images.githubusercontent.com/63272687/79084570-bfed6900-7d34-11ea-915c-4dede706a163.png)
